sudo: false
language: ruby
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
env:
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.1.0"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=4.1.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=4.2.0"
    - rvm: ruby-head
      env: "RAILS_VERSION=4.1.0"
    - rvm: ruby-head
      env: "RAILS_VERSION=4.2.0"

bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - gem update bundler

after_success:
  - bundle exec codeclimate-test-reporter
