sudo: false
language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head
env:
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.1.0"
  - "RAILS_VERSION=6.0.1"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:

bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - gem update bundler

after_success:
  - bundle exec codeclimate-test-reporter
